apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: local
  labels:
    k8s-app: alertmanager
data:
  alertmanager.yml: |
    global: 
      resolve_timeout: 1m
      slack_api_url: 'https://hooks.slack.com/services/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'
    receivers:
    - name: 'slack-notificaions'
      slack_configs:
      - channel: '#logging-demo'
        send_resolved: true
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: 'slack-notificaions'
      repeat_interval: 3h
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: local
  labels:
    k8s-app: alertmanager
spec:
  ports:
    - name: http
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    k8s-app: alertmanager
  type: "LoadBalancer"
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-operated
  namespace: local
  labels:
    k8s-app: alertmanager
spec:
  type: "ClusterIP"
  clusterIP: None
  selector:
    k8s-app: alertmanager
  ports:
    - name: mesh
      port: 6783
      protocol: TCP
      targetPort: 6783
    - name: http
      port: 9093
      protocol: TCP
      targetPort: 9093
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: local
  labels: &Labels
    k8s-app: alertmanager
spec:
  serviceName: "alertmanager-operated"
  replicas: 2
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
    spec:
      containers:
        - name: prometheus-alertmanager
          image: us-central1-docker.pkg.dev/gcp-sfhp-logmon-demo/hello-repo/alertmanager:v1
          imagePullPolicy: Always
          args:
            - --config.file=/etc/config/alertmanager.yml
            - --storage.path=/data
            - --web.listen-address=:9093
            - --web.route-prefix=/
            - --log.level=debug
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          ports:
            - containerPort: 9093
              name: http
            - containerPort: 6783
              name: mesh
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9093
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: alertmanager-local-data
              mountPath: "/data"
              subPath: ""
          resources:
            limits:
              cpu: 10m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
  volumeClaimTemplates:
  - metadata:
      name: alertmanager-local-data
    spec:
      storageClassName: elk
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "2Gi"
---
